name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: expense-manager.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          - name: Commit files # transfer the new html files back into the repository
      run: |
        git config --local user.name "erase-huz"
        git add ./docs
        git commit -m "Updating the repository GitHub html pages in the docs folder"
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
